### ISSUE TITLE
Task: Add LocalKeyVault configuration settings for Worker

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf-worker#169]
### What is the task about?

* This is part of https://github.com/vmware/repository-service-tuf/issues/207

* The LocalKeyVault configuration class method needs to be extended with the following parameters:

   - Optional `LOCAL_KEYVAULT_ONLINE_KEY`: inform the file name, default: `online.key`
   - Optional `LOCAL_KEYVAULT_ONLINE_KEY_PASSWORD`: inform the password/secret to load the online key
   - Optional `LOCAL_KEYVAULT_ONLINE_KEY_TYPE`: cryptography, default: `ed25519`
   
These keys will be used for implementing new functionalities in the LocalKeyVault type.

### Parent feature

- https://github.com/vmware/repository-service-tuf/issues/207

### References

[RFC: PEP 458 Simplifications](https://docs.google.com/document/d/1Z5zZnVy5D4nb_4wQc-lI417CjINr6-ykseqNTFgzUyc)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
To clarify: we are going to add only a single key called "online.key" because as @kairoaraujo has pointed out in his comment https://github.com/vmware/repository-service-tuf/issues/207#issuecomment-1378765633 we are going to use the same online key for `snapshot`, `timestamp` and `targets`.

**Comment by MVrachev** [comment]
Not sure why it was not closed.
Closed by #181
