### ISSUE TITLE
Task: Is the automatic `publish_targets` job is required?

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf-worker#175]
### What is the task about?

- This task issue was created from https://github.com/vmware/repository-service-tuf/issues/188
> Loading a huge amount of data will take a long time to process, and an automatic job in between will also try to update the existing/unpublished targets from the database. I will file an issue about it where we can discuss the best approach: do we need this job as each [add](https://github.com/vmware/repository-service-tuf-worker/blob/7225eff9a487c0dccd0e771a39403ea1fc96d8d9/repository_service_tuf_worker/repository.py#L539)/[remove](https://github.com/vmware/repository-service-tuf-worker/blob/7225eff9a487c0dccd0e771a39403ea1fc96d8d9/repository_service_tuf_worker/repository.py#L596) files its publish_target task? What happens if a failure occurs and it is not published?

Is the automatic `publish_targets` job required?

As mentioned above, every time targets are added/removed, after adding them to the RSTUF SQL DB, it triggers the `publish_targets`.

The `publish_targets` only helps if, for example, the targets were added/removed to the RSTUF SQL DB and, for some reason, the `publish_targets` is not triggered or started, it will guarantee that in about 60 seconds, a job will publish all unpublished targets.

However, we have task management, meaning that the requester can monitor the task and retrigger the add/remove targets.

Maybe even better to have an endpoint API to trigger the `publish_targets` and have the functionality even in the CLI admin.

### Parent feature

-  https://github.com/vmware/repository-service-tuf/issues/188

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
Feedback requested: @joshuagl, @MVrachev, @lukpueh, @KAUTH 

Here is my suggestion about this issue in specific.

The requester to add/remove targets has complete control over the tasks (even async) once they receive back the task id, and they can control the execution flow.

The flow about adding targets:

```mermaid
sequenceDiagram
    participant Requester
    participant API
    participant Broker
    Requester->>API: add/remove target(s)
    API->>Broker: Submit Task
    API->>Requester: task id
```
Using this task id, the requester can follow the execution.

The execution in the Worker will keep updating this task id with the status and progress.

I would suggest removing the automatic `publish_targets` call that runs every minute. 
https://github.com/vmware/repository-service-tuf-worker/blob/e75fec1e40d693caf181d8e069d490f3fe96dc8b/app.py#L143-L155

Some context on how it works for the Worker about adding/removing new targets

Note: Worker N, when N can be any Worker of multiples

```mermaid
sequenceDiagram
    participant Broker/Result Backend
    participant Worker N
    participant DB
    participant Storage Service
    Worker N-->>Broker/Result Backend: Get the Task to add/remove
    Worker N->>DB: Insert/update targets
    Worker N->>Broker/Result Backend: Update add/remove Task 
    Worker N->>Broker/Result Backend: submit sub-task `publish_targets `
    Worker N-->>Broker/Result Backend: Get the task `publish_targets `
    critical sub-task `publish_targets`
      Worker N->> Storage Service: Update `bins-{hash}`, Update Snapshot, Update Timestamp
      Worker N->> DB: Update SQL DB
    end
    Worker N->>Broker/Result Backend: Update add/remove Task FINISH
```

With this, the user will reprocess the request in case of failure.

We also need an endpoint in the REST API to trigger a `publish_targets`.
It is required by [Feature: data load for migrations](https://github.com/vmware/repository-service-tuf-worker/issues/188)
Because the CLI needs to do the following steps:
1. Insert all targets to SQL DB
2. Submit the Task to `publish_targets`

This could be used for other use cases (CLI command to 'force' `publish_targets`) but is not required there.

My suggestion is two actions:
- Add endpoint to trigger `publish_targets` in the Rest API
- Improve the task monitoring the sub-task, to have a better update for the user.

**Comment by kairoaraujo** [comment]
Just so you know – the issues above are required independently of the decision to remove the automatic publish targets.

**Comment by MVrachev** [comment]
> Just so you know – the issues above are required independently of the decision to remove the automatic publish targets.

I think that the decision for this task and whether we need a `publish_targets endpoint` is connected.
We won't need an endpoint if we leave it as it is.

I agree that more control over the user when to publish the targets is great.
The user can decide to make a bigger batch of new targets before publishing or make sure that his server is ultra-responsive and publish the targets every 20 seconds for example.
So, yes, if we add a new `publish targets` endpoint as suggested in an issue above, then I am all for removing the automatic job.

**Comment by kairoaraujo** [comment]
> > Just so you know – the issues above are required independently of the decision to remove the automatic publish targets.
> 
> I think that the decision for this task and whether we need a `publish_targets endpoint` is connected. We won't need an endpoint if we leave it as it is.
> 
> I agree that more control over the user when to publish the targets is great. The user can decide to make a bigger batch of new targets before publishing or make sure that his server is ultra-responsive and publish the targets every 20 seconds for example. So, yes, if we add a new `publish targets` endpoint as suggested in an issue above, then I am all for removing the automatic job.

Awesome @MVrachev ! 🎉 

I'm complementing what @MVrachev just said with another use case:
We don't know the user complexity flow about adding targets.
Imagine that he only makes the target available for the clients (publishing in some distribution platform or some release announcement) when they confirm that it is published in the TUF metadata.
The user loses control of when and by whom it was published as it was done by an automatic job that he cannot track.
We should let the user decide how re-process it: adding targets or triggering just the published targets.

**Comment by kairoaraujo** [comment]
> > I agree that more control over the user when to publish the targets is great. The user can decide to make a bigger batch of new targets before publishing or make sure that his server is ultra-responsive and publish the targets every 20 seconds for example. So, yes, if we add a new `publish targets` endpoint as suggested in an issue above, then I am all for removing the automatic job.

Rereading your comment, we could even create a new minor feature in the API/Worker.
It is not about the automatic job/routine but about publishing targets during the "add/remove targets" request.
Where we could have an option `publish_targets` as default `True`. It means, when you request "add/remove targets", it will publish it (after inserting it into RSTUF DB).
If you decide to move `publish_targets` as `False` it doesn't publish it in the TUF Metadata.

In that way, we could have the option you mentioned. Sending batches of targets and publishing them later.
WDYT @MVrachev

**Comment by MVrachev** [comment]
Maybe we can support both:
- an option: to publish changes to the targets when adding/removing targets
- an API endpoint

Even if we have the option to publish the targets I think it's worth adding an API call because how would you publish the targets if you have used `publish_targes = False` when you added/removed them?

Also, I start to think that the name of this option and API endpoint shouldn't be `publish_targets`, but the option could be called `publish_changes` and the call can still be `/api/v1/targets/publish`.

**Comment by kairoaraujo** [comment]
> Maybe we can support both:
> 
> * an option: to publish changes to the targets when adding/removing targets
> * an API endpoint
> 
> Even if we have the option to publish the targets I think it's worth adding an API call because how would you publish the targets if you have used `publish_targes = False` when you added/removed them?
> 
> Also, I start to think that the name of this option and API endpoint shouldn't be `publish_targets`, but the option could be called `publish_changes` and the call can still be `/api/v1/targets/publish`.

Yes, we will have both.
The endpoint is required due to the [feature load/import data](https://github.com/vmware/repository-service-tuf-cli/issues/39), the task issue is already opened: 
- https://github.com/vmware/repository-service-tuf-api/issues/242
The endpoint is defined as `/api/v1/targets/publish` as well.

I think we are well aligned.
I will file an issue with the optional parameter for add/remove.

**Comment by kairoaraujo** [comment]
Related tasks to close this issue:
- https://github.com/vmware/repository-service-tuf-worker/pull/197
- https://github.com/vmware/repository-service-tuf-worker/issues/198
- https://github.com/vmware/repository-service-tuf-api/issues/248

**Comment by MVrachev** [comment]
> Related tasks to close this issue:
> 
> * [x]  [Monitor publish tasks sub task and remove automatic job publishing targets #197](https://github.com/vmware/repository-service-tuf-worker/pull/197)
> * [x]  [feature: skip the `publish_targets` when field is `False` in the payload #198](https://github.com/vmware/repository-service-tuf-worker/issues/198)
> * [x]  [feature: add optional field `publish_targets` in add/remove payload repository-service-tuf-api#248](https://github.com/vmware/repository-service-tuf-api/issues/248)

All tasks are completed and we can close this issue.
Closing.
