### ISSUE TITLE
Make sure there is not undesirable changes in docker-compose.yml

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf-worker#55]
Uncomment:
https://github.com/kaprien/kaprien-repo-worker/blob/945ea61bdde31ddfb96dfa83abccd628cdefbfaf/docker-compose.yml#L27
Comment:
https://github.com/kaprien/kaprien-repo-worker/blob/945ea61bdde31ddfb96dfa83abccd628cdefbfaf/docker-compose.yml#L28

**Comment by MVrachev** [comment]
I can fix this one.
