### ISSUE TITLE
Use pinned hash GHA version in the Test Docker Build pipeline 

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf-worker#82]
https://github.com/vmware/repository-service-tuf-worker/blob/a14d694d756c528e91cf0a008fe0c2773e6d570e/.github/workflows/test_docker_build.yml#L12

https://github.com/vmware/repository-service-tuf-worker/blob/a14d694d756c528e91cf0a008fe0c2773e6d570e/.github/workflows/test_docker_build.yml#L12

https://github.com/vmware/repository-service-tuf-worker/blob/a14d694d756c528e91cf0a008fe0c2773e6d570e/.github/workflows/test_docker_build.yml#L18

https://github.com/vmware/repository-service-tuf-worker/blob/a14d694d756c528e91cf0a008fe0c2773e6d570e/.github/workflows/test_docker_build.yml#L21

https://github.com/vmware/repository-service-tuf-worker/blob/a14d694d756c528e91cf0a008fe0c2773e6d570e/.github/workflows/test_docker_build.yml#L24

**Comment by MVrachev** [comment]
Closed in https://github.com/vmware/repository-service-tuf-worker/pull/111
